name: Build

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots package --file pom.xml
      - name: Copy Jar file
        run: mv /home/runner/work/TheArcticData/TheArcticData/target/arctic-0.0.1-SNAPSHOT.jar app.jar
      - uses: actions/upload-artifact@master
        with:
          name: app.jar
          path: app.jar
        #- name: Build, Push and Release a Docker container to Heroku. # Your custom step name
        #uses: gonuit/heroku-docker-deploy@v1.3.3 # GitHub action name (leave it as it is).
          #with:

          #email: ${{ secrets.HEROKU_EMAIL }}

          #heroku_api_key: ${{ secrets.HEROKU_API_KEY }}

          #heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}


          #dockerfile_directory: ./

          #dockerfile_name: Dockerfile

          #docker_options: "--no-cache"

          #process_type: web