name: Deploy

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots package --file pom.xml
      - name: Copy Jar file
        run: mv /home/runner/work/TheArcticData/TheArcticData/target/arctic-0.0.1-SNAPSHOT.jar app.jar
      - uses: actions/upload-artifact@master
        with:
          name: jar-file
          path: app.jar